## Your First Deep Learning Project in Python
### Predicting Diabetes using NN

* We will use the NumPy library to load our dataset.
* We will use two classes from the Keras library to define our model.

In [1]:
# first neural network with keras tutorial
from numpy import loadtxt
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In this Keras tutorial, we are going to use the Pima Indians onset of diabetes dataset. 

This is a standard machine learning dataset from the UCI Machine Learning repository. It describes patient medical record data for Pima Indians and whether they had an onset of diabetes within five years.  
  
As such, it is a binary classification problem (onset of diabetes as 1 or not as 0). All of the input variables that describe each patient are numerical. This makes it easy to use directly with NN that expect numerical input and output values, and ideal for our first neural network in Keras.

The dataset is available from here:

> [pima-indians-diabetes.csv](https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv)  
> [Dataset Details](https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.names)

Let's now load the file as a matrix of numbers using the NumPy function loadtxt().

There are eight input variables and one output variable (the last column). We will be learning a model to map rows of input variables (X) to an output variable (y), which we often summarize as y = f(X).

The variables can be summarized as follows:

**Input Variables (X):**

1. Number of times pregnant
2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
3. Diastolic blood pressure (mm Hg)
4. Triceps skin fold thickness (mm)
5. 2-Hour serum insulin (mu U/ml)
6. Body mass index (weight in kg/(height in m)^2)
7. Diabetes pedigree function
8. Age (years)
9. Output Variables (y):

**Class variable (Y)**
1. `0` the patient has no diabetes.
2. `1` the patient has diabetes.

We can split the array into two arrays by selecting subsets of columns using the standard NumPy slice operator or “:”   

We can select the first 8 columns from index 0 to index 7 via the slice 0:8.  

We can then select the output column (the 9th variable) via index 8.

In [2]:
# load the dataset
dataset = loadtxt('data/pima-indians-diabetes.data.csv', delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]

In [3]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [4]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

## Define the model

Models in Keras are defined as a sequence of layers.

We create a Sequential model and add layers one at a time until we are happy with our network architecture.

The first thing to get right is to ensure the input layer has the right number of input features. This can be specified when creating the first layer with the input_dim argument and setting it to 8 for the 8 input variables.

**How do we know the number of layers and their types?**

This is a very hard question. There are heuristics that we can use and often the best network structure is found through a process of trial and error experimentation. 

Generally, you need a network large enough to capture the structure of the problem.

**In this example, we will use a fully-connected network structure with three layers.**

Fully connected layers are defined using the Dense class. We can specify the number of neurons or nodes in the layer as the first argument, and specify the *activation function* using the activation argument.

We will use the *rectified linear unit activation function* referred to as ReLU on the first two layers and the *Sigmoid function* in the output layer.

We use a sigmoid on the output layer to ensure our network output is between 0 and 1 and easy to map to either a probability of class 1 or snap to a hard classification of either class with a default threshold of 0.5.

We can piece it all together by adding each layer:


1. The model expects rows of data with 8 variables (the input_dim=8 argument)
2. The first hidden layer has 12 nodes and uses the relu activation function.
3. The second hidden layer has 8 nodes and uses the relu activation function.
4. The output layer has one node and uses the sigmoid activation function.

In [5]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

## Compile the model

Compiling the model uses the efficient numerical libraries under the covers (the so-called backend) such as Theano or TensorFlow. The backend automatically chooses the best way to represent the network for training and making predictions to run on your hardware, such as CPU or GPU or even distributed.

When compiling, we must specify some additional properties required when training the network. Remember training a network means finding the best set of weights to map inputs to outputs in our dataset.

We must specify the loss function to use to evaluate a set of weights, the optimizer is used to search through different weights for the network and any optional metrics we would like to collect and report during training.

We will learn about loss functions in Deep Learning next week.

For now, we will define the optimizer as the efficient stochastic gradient descent algorithm “adam“. 

Finally, because it is a classification problem, we will collect and report the classification accuracy, defined via the metrics argument.

In [6]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit Keras Model

We have defined our model and compiled it ready for efficient computation.

Now it is time to execute the model on some data.

We can train or fit our model on our loaded data by calling the `fit()` function on the model.

Training occurs over `epochs` and each epoch is split into `batches`.

**Epoch:** One pass through all of the rows in the training dataset.
**Batch:** One or more samples considered by the model within an epoch before weights are updated.

One `epoch` is comprised of one or more batches, based on the chosen batch size and the model is fit for many epochs. 

The training process will run for a fixed number of iterations through the dataset called epochs, that we must specify using the epochs argument. We must also set the number of dataset rows that are considered before the model weights are updated within each epoch, called the batch size and set using the batch_size argument.

For this problem, we will run for a small number of epochs (150) and use a relatively small batch size of 10.

These configurations can be chosen experimentally by trial and error. We want to train the model enough so that it learns a good mapping of rows of input data to the output classification. The model will always have some error, but the amount of error will level out after some point for a given model configuration. This is called model convergence.

In [7]:
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 0s 2ms/step - loss: 6.3149 - accuracy: 0.4557
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 2.2937 - accuracy: 0.5378
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 1.9393 - accuracy: 0.5365
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 1.6010 - accuracy: 0.5573
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 1.4584 - accuracy: 0.5677
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 1.2839 - accuracy: 0.5599
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1928 - accuracy: 0.5820
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 1.0986 - accuracy: 0.5938
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9794 - accuracy: 0.6133
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9366 - accuracy: 0.6094
Epoch 11/

## Evaluate Keras Model


We have trained our neural network on the entire dataset and we can evaluate the performance of the network on the same dataset.

This will only give us an idea of how well we have modeled the dataset (e.g. train accuracy), but no idea of how well the algorithm might perform on new data. We have done this for simplicity, but ideally, you could separate your data into train and test datasets for training and evaluation of your model.

You can evaluate your model on your training dataset using the `evaluate()` function on your model and pass it the same input and output used to train the model.

This will generate a prediction for each input and output pair and collect scores, including the average loss and any metrics you have configured, such as accuracy.

The `evaluate()` function will return a list with two values. The first will be the loss of the model on the dataset and the second will be the accuracy of the model on the dataset. We are only interested in reporting the accuracy, so we will ignore the loss value.

In [8]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

24/24 [==============================] - 0s 2ms/step - loss: 0.4648 - accuracy: 0.7812
Accuracy: 78.12


## Make Predictions

After the model is trained, how can we make predictions on new data?

We can adapt the above example and use it to generate predictions on the training dataset, pretending it is a new dataset we have not seen before.

Making predictions is as easy as calling the `predict()` function on the model. We are using a sigmoid activation function on the output layer, so the predictions will be a probability in the range between 0 and 1. We can easily convert them into a crisp binary prediction for this classification task by rounding them.

In [9]:
# make probability predictions with the model
predictions = model.predict(X)
# round predictions 
rounded = [round(x[0]) for x in predictions]

Alternately, we can call the `predict_classes()` function on the model to predict crisp classes directly.

In [10]:
# make class predictions with the model
predictions = model.predict_classes(X)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [11]:
predictions

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

## RECAP

- Load the data.
- Define a neural network in Keras.
- Compile a Keras model using the efficient numerical backend.
- Train a model on data.
- Evaluate a model on data.
- Make predictions with the model.